name: replace in file
description: replaces word in file

inputs:
  ParamsEnv:
    required: true
    description: string of aws parameters like in a .env file format
  FileName:
    required: true
    description: json string of task definition

runs:
  using: node16
  main: dist/index.js
